blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("post.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("comments/", include("comment.urls", namespace="comments")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path

from .views import CommentCreateView

app_name = "comment"
urlpatterns = [
    path(
        "create/<str:content_type>/<int:object_id>/",
        CommentCreateView.as_view(),
        name="comment-create",
    )
]

post/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy

from .views import (
    BaseView,
    ChangeProfilePictureView,
    CreatePostView,
    EditPostView,
    EditProfileView,
    LoginView,
    PostDetailView,
    ProfileView,
    RegistrationView,
    TagDetailView,
)

app_name = "post"
urlpatterns = [
    path("", BaseView.as_view(), name="base"),
    path("post_detail/<slug:slug>", PostDetailView.as_view(), name="post_detail"),
    path("tag_detail/<slug:slug>", TagDetailView.as_view(), name="tag_detail"),
    path("login", LoginView.as_view(), name="login"),
    path(
        "logout", LogoutView.as_view(next_page=reverse_lazy("post:base")), name="logout"
    ),
    path("registration", RegistrationView.as_view(), name="registration"),
    path("profile/<slug:slug>", ProfileView.as_view(), name="profile"),
    path("profile/<slug:slug>/edit", EditProfileView.as_view(), name="edit_profile"),
    path(
        "profile/<slug:slug>/change_picture",
        ChangeProfilePictureView.as_view(),
        name="change_picture",
    ),
    path("create_post", CreatePostView.as_view(), name="create_post"),
    path("edit_post/<slug:slug>", EditPostView.as_view(), name="edit_post"),
]

comment/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from post.models import Profile


class Comment(models.Model):
    """Комментарий"""

    author = models.ForeignKey(
        Profile, verbose_name="Автор комментария", on_delete=models.CASCADE
    )
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    text = models.TextField(verbose_name="Текст комментария")
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return f"{self.id}"

    class Meta:
        ordering = ("-created_at",)

post/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import SmartResize


class Post(models.Model):
    """Отдельная статья"""

    title = models.CharField(
        max_length=127, verbose_name="Название", db_index=True, unique=True
    )
    description = models.CharField(max_length=511, verbose_name="Описание поста")
    image_thumbnail = ProcessedImageField(
        upload_to="pictures/",
        processors=[SmartResize(600, 400)],
        format="JPEG",
        options={"quality": 60},
    )
    slug = models.SlugField(unique=True, max_length=127)
    tags = models.ManyToManyField("Tag", verbose_name="Tags")
    author = models.ForeignKey(
        "Profile", verbose_name="Автор", on_delete=models.PROTECT
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)
    content = models.TextField(verbose_name="Содержание")
    description_for_search_engines = models.CharField(max_length=511, blank=True)
    is_published = models.BooleanField(default=True)
    comments = GenericRelation("comment.Comment")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.description_for_search_engines:
            self.description_for_search_engines = self.description
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("post:post_detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ("is_published", "-pub_date")


class Tag(models.Model):
    """Категории статей"""

    name = models.CharField(max_length=100, verbose_name="Имя tag'а", db_index=True)
    slug = models.SlugField(unique=True)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("post:tag_detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ("name",)


class Profile(models.Model):
    """Профиль пользователя"""

    user = models.OneToOneField(
        User, verbose_name="Пользователь", on_delete=models.CASCADE
    )
    slug = models.SlugField(unique=True, blank=True)
    bio = models.CharField(
        max_length=511, verbose_name="Краткая информация об авторе", blank=True
    )
    author = models.BooleanField("Автор", default=False)
    avatar_thumbnail = ProcessedImageField(
        upload_to="avatars/",
        processors=[SmartResize(300, 300)],
        format="JPEG",
        options={"quality": 60},
        default="avatars/default-avatar.jpg",
    )

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.user.username
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("post:profile", kwargs={"slug": self.slug})

post/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import AnonymousUser, User
from django.forms.models import model_to_dict
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views import View, generic
from slugify import slugify

from comment.forms import CommentForm

from .forms import (
    ChangeProfilePictureForm,
    CreatePostForm,
    EditPostForm,
    EditProfileForm,
    LoginForm,
    RegistrationForm,
)
from .mixins import DefaultContextMixin
from .models import Post, Profile, Tag


class BaseView(DefaultContextMixin, generic.ListView):
    """Основная страница"""

    model = Post
    paginate_by = 3
    template_name = "post/base.html"
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        return super().get_context_data(self.request, **kwargs)


class PostDetailView(DefaultContextMixin, generic.DetailView):
    """Отдельная статья"""

    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(self.request, **kwargs)
        context["user"] = self.request.user
        context["form"] = CommentForm()
        return context


class TagDetailView(DefaultContextMixin, generic.DetailView):
    """Отдельный tag"""

    model = Tag
    context_object_name = "main_tag"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(self.request, **kwargs)
        context["posts"] = Tag.objects.get(slug=context["main_tag"].slug).post_set.all()
        return context


class LoginView(View):
    """Авторизация"""

    def get(self, *args, **kwargs):
        form = LoginForm()
        context = {
            "form": form,
        }
        return render(self.request, "post/login.html", context)

    def post(self, *args, **kwargs):
        form = LoginForm(self.request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user:
                login(self.request, user)
            messages.success(
                self.request,
                f"Добро пожаловать, {user.first_name if user.first_name else user.username}!",
            )
            return redirect(reverse("post:base"))
        context = {
            "form": form,
        }
        return render(self.request, "post/login.html", context)


class RegistrationView(View):
    """Регистрация"""

    def get(self, *args, **kwargs):
        form = RegistrationForm()
        context = {
            "form": form,
        }
        return render(self.request, "post/registration.html", context)

    def post(self, *args, **kwargs):
        form = RegistrationForm(self.request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.username = form.cleaned_data["username"]
            new_user.email = form.cleaned_data["email"]
            new_user.first_name = form.cleaned_data["first_name"].title()
            new_user.last_name = form.cleaned_data["last_name"].title()
            new_user.save()
            new_user.set_password(form.cleaned_data["password"])
            new_user.save()
            Profile.objects.create(user=new_user, slug=slugify(new_user.username))
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            login(self.request, user)
            messages.success(
                self.request,
                f"Добро пожаловать, {user.first_name if user.first_name else user.username}! с:",
            )
            return redirect(reverse("post:base"))
        context = {
            "form": form,
        }
        return render(self.request, "post/registration.html", context)


class ProfileView(DefaultContextMixin, generic.DetailView):
    """Подробная информация о пользователе"""

    model = Profile
    template_name_suffix = ""
    context_object_name = "main_profile"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(self.request, **kwargs)
        context["user"] = self.request.user
        context["articles"] = Profile.objects.get(
            user=context["main_profile"].user
        ).post_set.order_by("pub_date")
        return context


class EditProfileView(View):
    """Настройки профиля"""

    def get(self, *args, **kwargs):
        if isinstance(self.request.user, AnonymousUser):
            messages.warning(self.request, "У вас недостаточно прав!")
            return redirect(reverse("post:base"))
        elif Profile.objects.get(user=self.request.user) != Profile.objects.get(
            slug=kwargs["slug"]
        ):
            messages.warning(
                self.request, "Вы можете редактировать только свой профиль!"
            )
            return redirect(reverse("post:base"))
        profile = Profile.objects.get(slug=kwargs["slug"])
        data = model_to_dict(profile.user)
        data.update(bio=profile.bio)
        form = EditProfileForm(initial=data)
        context = {
            "profile": profile,
            "form": form,
        }
        return render(self.request, "post/profile_settings.html", context)

    def post(self, *args, **kwargs):
        profile = Profile.objects.get(slug=kwargs["slug"])
        user = profile.user
        form = EditProfileForm(self.request.POST, user=user)
        if form.is_valid():
            User.objects.filter(pk=user.pk).update(
                username=form.cleaned_data["username"],
                email=form.cleaned_data["email"],
                first_name=form.cleaned_data["first_name"].title(),
                last_name=form.cleaned_data["last_name"].title(),
            )
            user.set_password(form.cleaned_data["password"])
            user.save(update_fields=["password"])
            Profile.objects.filter(user=user).update(bio=form.cleaned_data["bio"])
            messages.success(self.request, "Ваш профиль успешно обновлен с:")
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            login(self.request, user)
            return redirect(reverse("post:base"))
        context = {
            "profile": profile,
            "form": form,
        }
        return render(self.request, "post/profile_settings.html", context)


class ChangeProfilePictureView(generic.UpdateView):
    """Сменить аватар"""

    model = Profile
    form_class = ChangeProfilePictureForm
    template_name = "post/change_profile_picture.html"

    def get(self, *args, **kwargs):
        if isinstance(self.request.user, AnonymousUser) or Profile.objects.get(
            user=self.request.user
        ) != Profile.objects.get(slug=kwargs["slug"]):
            messages.warning(self.request, "У вас недостаточно прав!")
            return redirect(reverse("post:base"))
        return super().get(*args, **kwargs)

    def form_valid(self, form):
        profile = form.save(commit=False)
        profile.avatar_thumbnail = form.cleaned_data["avatar_thumbnail"]
        profile.save(update_fields=("avatar_thumbnail",))
        messages.success(self.request, "Аватар успешно обновлен!")
        return redirect(reverse("post:profile", kwargs={"slug": self.kwargs["slug"]}))


class CreatePostView(DefaultContextMixin, generic.CreateView):
    """Создать пост"""

    model = Post
    form_class = CreatePostForm
    template_name = "post/create_post.html"

    def get(self, *args, **kwargs):
        if (
            isinstance(self.request.user, AnonymousUser)
            or not Profile.objects.get(user=self.request.user).author
        ):
            messages.warning(self.request, "У вас недостаточно прав!")
            return redirect(reverse("post:base"))
        return super().get(*args, **kwargs)

    def form_valid(self, form):
        post = Post.objects.create(
            title=form.cleaned_data["title"],
            slug=slugify(form.cleaned_data["title"]),
            content=form.cleaned_data["content"],
            author=Profile.objects.get(user=self.request.user),
            image_thumbnail=form.cleaned_data["image_thumbnail"],
            description=form.cleaned_data["description"],
            description_for_search_engines=form.cleaned_data["description"],
            is_published=False,
            pub_date=timezone.now(),
            edit_date=timezone.now(),
        )
        post.tags.add(*form.cleaned_data["tags"])
        messages.success(
            self.request,
            "Ваш пост успешно создан с:\nАдминистрация проверит его и опубликует!",
        )
        return redirect(
            reverse(
                "post:profile", kwargs={"slug": slugify(self.request.user.username)}
            )
        )

    def get_context_data(self, **kwargs):
        return super().get_context_data(self.request)


class EditPostView(DefaultContextMixin, View):
    """Редактировать пост"""

    def get(self, *args, **kwargs):
        if (
            isinstance(self.request.user, AnonymousUser)
            or Post.objects.get(slug=kwargs["slug"]).author.user != self.request.user
        ):
            messages.warning(self.request, "У вас недостаточно прав!")
            return redirect(reverse("post:base"))
        data = model_to_dict(Post.objects.get(slug=kwargs["slug"]))
        form = EditPostForm(initial=data)
        context = {
            "form": form,
        }
        context.update(self.get_context_data(self.request, **kwargs))
        return render(self.request, "post/edit_post.html", context)

    def post(self, *args, **kwargs):
        post = Post.objects.get(slug=kwargs["slug"])

post/templates/post/base.html
<!doctype html>
<html lang="en" class="h-100">
<head>
    {% load imagekit %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="generator" content="Hugo 0.88.1">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <title>
        {% block title %}
            UkiBlog | Articles on all topics
        {% endblock %}
    </title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/cover/">
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">

    <style>
        body {
            font-size: 18px;
        }

        h2 {
            font-size: 24px;
        }

        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }


    </style>
    <link href="cover.css" rel="stylesheet">
</head>
<body class="d-flex h-100 bg-dark">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <div class="mb-auto">
        {% block navbar %}
            <header class="p-3 bg-dark text-white">
                <div class="container">
                    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                        <h1 class="me-4 pe-7">
                            <a href="{% url 'post:base' %}"
                               class="text-start text-decoration-none text-white">UkiBlog</a>
                        </h1>

                        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                            <li><a href="{% url 'post:logout' %}" class="nav-link px-2 text-secondary">Home</a></li>
                            <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
                        </ul>

                        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                            <input type="search" class="form-control form-control-dark" placeholder="Search..."
                                   aria-label="Search">
                        </form>
                        {% block profile %}
                            <div class="text-end">
                                {% if request.user.is_authenticated %}
                                    <a href="{{ profile.get_absolute_url }}"
                                       class="text-decoration-none text-white text-start">
                                        <img src="{{ profile.avatar_thumbnail.url }}" alt="" width="32" height="32"
                                             class="rounded-circle me-2">{{ profile.user.username }}
                                    </a>
                                {% else %}
                                    <a href="{% url 'post:login' %}" class="text-decoration-none">
                                        <button type="button" class="btn btn-outline-light me-2">Login</button>
                                    </a>
                                    <a href="{% url 'post:registration' %}" class="text-decoration-none">
                                        <button type="button" class="btn btn-warning">Sign-up</button>
                                    </a>
                                {% endif %}
                            </div>
                        {% endblock %}
                    </div>
                </div>
            </header>
            {% if messages %}
                <br>
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert"
                         style="margin-left: 450px; width: 900px;">
                        <strong>{{ message }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
        {% endblock %}
        <br>
        {% block categories %}
            <div class="card" style="width: 18rem; float: right; margin: 0 200px 0 30px">
                <div class="card-header">
                    Категории
                </div>
                <ul class="list-group list-group-flush">
                    {% for tag in tags %}
                        <li class="list-group-item">
                            <a href="{{ tag.get_absolute_url }}" class="text-decoration-none text-dark me-1">
                                <span class="text-primary">#</span>{{ tag.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endblock %}
        {% block main %}
            <main class="px-3 text-dark" style="margin-left: 450px; width: 900px;">
                {% for post in page_obj %}
                    <div class="card text-center">
                        <div class="card-header">
                            <a href="{{ post.author.get_absolute_url }}" class="text-decoration-none text-dark"
                               style="font-weight: 600">
                                <img src="{{ post.author.avatar_thumbnail.url }}" alt="" width="32" height="32"
                                     class="rounded-circle me-2">{{ post.author.user.username }}
                            </a>
                            <span class="text-muted">
                        {{ post.pub_date|date:"H:i d.m.Y" }}
                                {% if post.pub_date != post.edit_date %}
                                    (ред.
                                    {% if post.pub_date|date:"d.m.Y" == post.edit_date|date:"d.m.Y" %}
                                        в {{ post.edit_date|date:"H:i" }}
                                    {% else %}
                                        {{ post.edit_date|date:"H:i d.m.Y" }}
                                    {% endif %}
                                    )
                                {% endif %}
                    </span>
                        </div>
                        <div class="card-body">
                            <h2 class="card-title"><a href="{{ post.get_absolute_url }}"
                                                      class="text-decoration-none text-dark">
                                {{ post.title }}</a></h2>
                            {% for tag in post.tags.all %}
                                <a href="{{ tag.get_absolute_url }}" class="text-decoration-none text-dark me-1">
                                    <span class="text-primary">#</span>{{ tag.name }}</a>
                            {% endfor %}
                            <br>
                            <img src="{{ post.image_thumbnail.url }}" width=600px style="margin: 15px 0;" alt="">
                            <p class="card-text text-dark">{{ post.description }}</p>
                            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Читать полностью</a>
                        </div>
                    </div>
                    <br>
                {% endfor %}
                <nav aria-label="Page navigation example" class="mt-5">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
                            </li>
                        {% endif %}
                        {% for n in page_obj.paginator.page_range %}
                            {% if page_obj.number == n %}
                                <li class="page-item active">
                                    <a href="?page={{ n }}" class="page-link">{{ n }}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a href="?page={{ n }}" class="page-link">{{ n }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>

            </main>
        {% endblock %}
        {% block js %}
        {% endblock %}
        {% block footer %}
            <footer class="text-center text-white-50 mt-5 mb-5">
                <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a
                        href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
            </footer>
        {% endblock %}
    </div>
</div>
</body>
</html>

post/templates/post/login.html
{% extends 'post/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Авторизация | Ukiblog
{% endblock %}
{% block categories %}
{% endblock %}
{% block main %}
<div class="card" style="width: 650px; margin: 100px 600px 300px 600px; padding: 50px 100px">
    <div class="card-body">
        <h3 class="text-center">Авторизация</h3>

        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <div class="d-grid gap-2 col-6 mx-auto"><input type="submit" class="btn btn-success btn-lg" value="Войти"></div>
        </form>
    </div>
</div>
{% endblock %}

post/templates/post/post_detail.html
{% extends 'post/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block description %}
    {{ post.description_for_search_engines }}
{% endblock %}
{% block main %}
    <main class="px-3 text-dark" style="margin-left: 450px; width: 900px;">
    <div class="card text-center">
        <div class="card-header">
            <a href="#" class="text-decoration-none text-dark" style="font-weight: 600">
                <img src="{{ post.author.avatar_thumbnail.url }}" alt="" width="32" height="32"
                     class="rounded-circle me-2">{{ post.author.user.username }}
            </a>
            <span class="text-muted">
                        {{ post.pub_date|date:"H:i d.m.Y" }}
                {% if post.pub_date != post.edit_date %}
                    (ред.
                    {% if post.pub_date|date:"d.m.Y" == post.edit_date|date:"d.m.Y" %}
                        в {{ post.edit_date|date:"H:i" }}
                    {% else %}
                        {{ post.edit_date|date:"H:i d.m.Y" }}
                    {% endif %}
                    )
                {% endif %}
                    </span>
            {% if post.author.user == user %}
                <a href="{% url 'post:edit_post' slug=post.slug %}" class="text-decoration-none">
                    <button type="button" class="btn btn-outline-primary btn-lg" style="margin-left: 200px">
                        Редактировать
                    </button>
                </a>
            {% endif %}
        </div>
        <div class="card-body">
            <h2 class="card-title text-dark">
                {{ post.title }}
            </h2>
            {% for tag in post.tags.all %}
                <a href="{{ tag.get_absolute_url }}" class="text-decoration-none text-dark me-1">
                    <span class="text-primary">#</span>{{ tag.name }}</a>
            {% endfor %}
            <img src="{{ post.image_thumbnail.url }}" width=600px style="margin: 15px 0;" alt="">
            <hr>
            <div class="text-start">
                {% autoescape off %}
                    <p class="card-text">{{ post.content }}</p>
                {% endautoescape %}
                <hr>
                <p><strong>Комментарии</strong>: <span
                        class="badge rounded-pill bg-dark">{{ post.comments.count }}</span></p>
                <hr>
                {% if request.user.is_authenticated %}
                    <form action="{% url 'comment:comment-create' content_type="post" object_id=post.id %}"
                          method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <br>
                        <input class="btn btn-primary" type="submit" id="send-comment" value="Отправить">
                    </form>
                {% else %}
                    <p class="text-center">Оставлять комментарии могут только авторизованные пользователи</p>
                {% endif %}
                <hr>
                <div class="row" id="comments-list">
                    {% for comment in post.comments.all %}
                        <div class="col-md-12 mt-3 mb-3">
                            <p><a href="{{ comment.author.get_absolute_url }}" class="text-decoration-none text-dark"
                                  style="font-weight: 600">
                                <img src="{{ comment.author.avatar_thumbnail.url }}" alt="" width="32" height="32"
                                     class="rounded-circle me-2">{{ comment.author.user.username }}
                            </a>|
                                <small>{{ comment.created_at|date:"H:i d.m.Y" }}</small></p>
                            <p>{{ comment.text }}</p>
                        </div>
                        <br>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        const commentsSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/post_detail/'
            + "{{ post.id }}"
            + '/'
        );
        commentsSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            commentsList = document.getElementById('comments-list')
            commentsList.insertAdjacentHTML(
                'beforeend',
                '<div class="col-md-12 mt-3 mb-3">\n' +
                '<p><strong>' + data['message']['author'] + '</strong> | <small>опубликовано:' + data['message']['created_at'] + '</small></p>\n' +
                '<p>' + data['message']['text'] + '</p>\n' +
                '</div>'
            )
        };
        document.querySelector('#send-comment').onclick = function (e) {
            e.preventDefault()
            const messageInputDom = document.querySelector('#id_text');
            const text = messageInputDom.value;
            commentsSocket.send(JSON.stringify({
                'text': text
            }));
            messageInputDom.value = '';
        };

    </script>
{% endblock js %}

</main>